version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/calendar_site
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - post_gres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=calendar_events_db
      - POSTGRES_USER=events_user
      - POSTGRES_PASSWORD=events_password

volumes:
  post_gres_data:

