# Generated by Django 4.2.6 on 2023-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_registereduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
