# Generated by Django 4.2.6 on 2023-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registereduser_is_admin_registereduser_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_by_mods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event name', max_length=255),
        ),
    ]
