# Generated by Django 4.2.6 on 2023-11-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_category_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='surname',
        ),
        migrations.AddField(
            model_name='category',
            name='accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_accepted', to='events.worker'),
        ),
        migrations.AddField(
            model_name='category',
            name='approved_by_mods',
            field=models.BooleanField(default=False),
        ),
    ]
