# Generated by Django 4.2.6 on 2023-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_registereduser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='images/events/<django.db.models.fields.AutoField>/'),
        ),
    ]
