# Generated by Django 4.2.6 on 2023-11-14 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventestimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:30'),
        ),
        migrations.AlterField(
            model_name='eventestimation',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='photo',
            field=models.ImageField(null=True, upload_to='Photos/places/%y/%m/%d/'),
        ),
    ]
