# Generated by Django 4.2.6 on 2023-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventestimation_created_at_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventplace',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='eventplace',
            name='photo',
        ),
        migrations.AddField(
            model_name='eventplace',
            name='approved_by_mods',
            field=models.BooleanField(default=False),
        ),
    ]
