# Generated by Django 4.2.6 on 2023-11-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_eventplace_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpayment',
            name='accepted',
        ),
    ]
