# Generated by Django 4.2.6 on 2023-11-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_ticketpayment_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(null=True),
        ),
    ]
