# Generated by Django 4.2.6 on 2023-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventestimation',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
